import Ember from 'ember';

export default Ember.Service.extend({

  "AGOL_DEFAULT_THUMBNAIL_FILE_NAMES":[
    "thumbnail/thumbnail.jpeg",
    "thumbnail/nullThumbnail.png",
    "thumbnail/no-user-thumb.jpg",
    "thumbnail/ago_downloaded.png",
    "thumbnail/ago_downloaded.jpg"
  ],
  "AGOL_USER_PROFILE_THUMBNAIL_NAMES":[
    "thumbnail.jpeg",
    "nullThumbnail.png",
    "no-user-thumb.jpg",
    "ago_downloaded.png",
    "ago_downloaded.jpg"
  ],
  "APP_ID":"niKa0quIDVUw0iUf",
  "ARCGIS_URL":"www.arcgis.com/sharing/rest/content/items",
  "CURATION_GROUPS":"services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/curation_groups/FeatureServer/0",
  "CURATOR_LIST":"services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/curlist/FeatureServer/0",
  "DONUT_TEXT_FILL_COLOR":"#a2a2a2",
  "DONUT_TEXT_FONT_SIZE":"20",
  "ITEM_SNIPPET_PROHIBITED_WORDS":[
    "copy",
    "demo",
    "test",
    "eval"
  ],
  "LIVING_ATLAS_TAGS":[
    "imagery",
    "baseimagery",
    "multispectral",
    "temporal",
    "event_imagery",
    "basemap",
    "esri_basemap",
    "partner_basemap",
    "user_basemap",
    "historical",
    "demographics",
    "income",
    "spending",
    "behaviors",
    "population",
    "housing",
    "business",
    "jobs",
    "poverty",
    "at risk",
    "landscape",
    "agriculture",
    "climate",
    "weather",
    "ecology",
    "species",
    "disturbance",
    "elevation",
    "landcover",
    "hazards",
    "soils",
    "geology",
    "subsurface",
    "water",
    "oceans",
    "earth observations",
    "urban",
    "3D",
    "3d",
    "movement",
    "parcels",
    "people",
    "planning",
    "public",
    "work",
    "transportation",
    "accessibility",
    "infrastructure",
    "logistics",
    "traffic",
    "transit",
    "boundaries",
    "places",
    "story map",
    "story maps"
  ],
  "LIVING_ATLAS_TAGS_PROHIBITED":[
    "copy",
    "demo",
    "test",
    "eval"
  ],
  "MONTHS":[
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ],
  "NOMINATED_ITEMS":"//services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/nomcur/FeatureServer/0",
  "SCORING_MESSAGES":{
    "ERRORS":{
      "ACCESS_USE_CONSTRAINTS":{

      },
      "CREDITS":{

      },
      "DESCRIPTION":{
        "MISSING_DESCRIPTION":"MISSING description"
      },
      "LAYER_COUNT":{
        "ERROR":"FATAL ERROR: CHECK ITEM"
      },
      "SHARING":{
        "ORG":"Sharing is ORGANIZATION",
        "PRIVATE":"Sharing is PRIVATE"
      },
      "SSL":{

      },
      "SUMMARY":{
        "MISSING_SUMMARY":"MISSING summary"
      },
      "TAGS":{
        "MINIMUM_NUMBER_OF_LA_TAGS":"At least 1 Living Atlas tag is <b>required</b>",
        "MINIMUM_NUMBER_OF_TAGS":"This item only has {numTags} out of 4 required tags total",
        "PROHIBITED_TAGS":"Contains PROHIBITED tags"
      },
      "THUMBNAILS":{
        "LARGE_THUMBNAIL_ERROR":"MISSING large thumbnail",
        "SMALL_THUMBNAIL_ERROR":"MISSING small thumbnail"
      },
      "TITLE":{
        "MISSING_TITLE":"MISSING title"
      },
      "USER_PROFILE_DESCRIPTION":{
        "MISSING":"Profile MISSING description"
      },
      "USER_PROFILE_NAME":{

      },
      "USER_PROFILE_THUMBNAIL":{

      }
    },
    "WARNINGS":{
      "ACCESS_USE_CONSTRAINTS":{
        "MISSING":"MISSING Access/Use information",
        "NO_LINKS":"Access/Use information contains no links",
        "TOO_SHORT":"Access/Use information too short"
      },
      "CREDITS":{
        "MISSING":"MISSING credits information"
      },
      "DESCRIPTION":{
        "NO_LINKS":"Description has no links",
        "TOO_SHORT":"Description too short"
      },
      "LAYER_COUNT":{
        "BETTER":"There are between 2 and 10 layers",
        "GOOD":"Exceeds 10 layers"
      },
      "SHARING":{

      },
      "SSL":{
        "DISABLED":"No SSL"
      },
      "SUMMARY":{
        "SUMMARY_PROHIBITED_CHARS":"Summary contains prohibited characters",
        "SUMMARY_PROHIBITED_TEXT":"Summary contains prohibited text",
        "SUMMARY_TOO_SHORT":"Summary too short"
      },
      "TAGS":{

      },
      "THUMBNAILS":{

      },
      "TITLE":{
        "TITLE_CASE":"Title cannot be all uppercase",
        "TITLE_PROHIBITED_CHARS":"Title contains a prohibited character",
        "TITLE_PROHIBITED_TEXT":"Title contains a prohibited word",
        "TITLE_TOO_SHORT":"Title too short"
      },
      "USER_PROFILE_DESCRIPTION":{
        "MIN_NUM_SENTENCES":"Profile description does not contain the minimum number of sentences",
        "MIN_WORD_COUNT":"Profile description does not contain the minimum number of words",
        "NO_EMAIL":"Profile description does not contain an email",
        "NO_LINK":"Profile description does not contain a link"
      },
      "USER_PROFILE_NAME":{
        "MIN_LENGTH":"Profile full name does not meet the minimum length",
        "PROHIBITED_CHAR":"Profile full name contains a prohibited character"
      },
      "USER_PROFILE_THUMBNAIL":{
        "NO_THUMBNAIL":"Profile MISSING thumbnail"
      }
    },
    "LABELS": {
      "THUMBNAILS" : "Thumbnails",
      "TITLE" : "Title",
      "SUMMARY" : "Summary",
      "DESCRIPTION" : "Description",
      "ACCESS_USE_CONSTRAINTS" : "Access\/Use",
      "CREDITS" : "Credits",
      "TAGS" : "Tags",
      "SHARING" : "Sharing",
      "LAYER_COUNT" : "Layer Count",
      "SSL" : "SSL",
      "USER_PROFILE_NAME" : "Profile Name",
      "USER_PROFILE_DESCRIPTION" : "Profile Description",
      "USER_PROFILE_THUMBNAIL" : "Profile Thumbnail"
    }
  },
  "SDG_STAGING_GROUP":"af18b71f8e6244fea17760c355651962",
  "SHARING_COMMUNITY_URL":"www.arcgis.com/sharing/rest/community/users/",
  "SHARING_HOST":"https://www.arcgis.com",
  "VALIDATE_BUTTON_CLICKED":false,
  "VALID_TYPES":[
    "Web Map",
    "Map Service",
    "Feature Collection",
    "Feature Service",
    "Image Service",
    "Web Scene",
    "CityEngine Web Scene",
    "Web Mapping Application",
    "Rule Package",
    "Vector Tile Service",
    "Geoprocessing Service",
    "Mobile Application",
    "Document Link",
    "Layer package",
    "WMS"
  ],
  "curator":{

  },
  "curatorList":[

  ],
  "curatorStore":{

  },
  "groupChartData":[

  ],
  "groupsStore":{

  },
  "myContentFolders":[

  ],
  "portal":{

  },
  "portalUser":{

  },
  "portalUserCredentials":{

  },
  "scoring":{
    "CITY_ENGINE_WEB_SCENE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":0
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":6,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":2,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":3
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":8
      }
    },
    "DEFAULT":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":0
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":6,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":2,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":3
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":8
      }
    },
    "DOCUMENT_LINK":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":4
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "FEATURE_COLLECTION":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "FEATURE_SERVICE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "GEOPROCESSING_SERVICE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":4
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "IMAGE_SERVICE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "LAYER_PACKAGE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":0
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":6,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":2,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":3
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":8
      }
    },
    "MAP_SERVICE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "MOBILE_APPLICATION":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":4
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "RULE_PACKAGE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":0
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":6,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":2,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":3
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":8
      }
    },
    "VECTOR_TILE_SERVICE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "WEB_MAP":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":8
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":5,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":8,
        "LAYER_COUNT_BETTER_SCORE":4,
        "LAYER_COUNT_GOOD_SCORE":1
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":2
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":7
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":3
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":4
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":2,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "WEB_MAPPING_APPLICATION":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":4
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    },
    "WEB_SCENE":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":0
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":6,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":2,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":3
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":8
      }
    },
    "WMS":{
      "ACCESS_INFORMATION":{
        "MUST_EXIST_SCORE":9
      },
      "DESCRIPTION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "LAYER_COUNT":{
        "LAYER_COUNT_BEST_SCORE":0,
        "LAYER_COUNT_BETTER_SCORE":0,
        "LAYER_COUNT_GOOD_SCORE":0
      },
      "LICENSE_INFORMATION":{
        "HAS_LINK_SCORE":2,
        "MIN_LENGTH_SCORE":6,
        "MUST_EXIST_SCORE":1
      },
      "SHARING":{
        "ORG":2,
        "PRIVATE":0,
        "PUBLIC":8
      },
      "SSL":{
        "SSL_DISABLED":0,
        "SSL_ENABLED":4
      },
      "SUMMARY":{
        "MIN_LENGTH_SCORE":4,
        "MUST_EXIST_SCORE":1,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":1
      },
      "TAGS":{
        "MIN_LAW_TAGS_LENGTH_SCORE":4,
        "MIN_LENGTH_SCORE":4,
        "NO_PROHIBITED_TAGS_SCORE":2
      },
      "THUMBNAILS":{
        "HAS_CUSTOM_LARGE":5,
        "HAS_CUSTOM_SMALL":5
      },
      "TITLE":{
        "MIN_LENGTH_SCORE":2,
        "NO_ALL_CAPS_SCORE":2,
        "NO_PROHIBITED_WORDS_SCORE":3,
        "NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_DESCRIPTION":{
        "USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION":1,
        "USER_PROFILE_DESCRIPTION_HAS_EMAIL":2,
        "USER_PROFILE_DESCRIPTION_HAS_LINK":1,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES":2,
        "USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS":1
      },
      "USER_PROFILE_FULLNAME":{
        "HAS_FULLNAME_SCORE":5,
        "HAS_NO_UNDERSCORE_SCORE":2
      },
      "USER_PROFILE_THUMBNAIL":{
        "USER_PROFILE_HAS_THUMBNAIL":7
      }
    }
  },
  "selectedMyContentFolders":[

  ],
  "supportedTypes":{
    "CITY_ENGINE_WEB_SCENE":"CityEngine Web Scene",
    "DOCUMENT_LINK":"Document Link",
    "FEATURE_COLLECTION":"Feature Collection",
    "FEATURE_SERVICE":"Feature Service",
    "GEOPROCESSING_SERVICE":"Geoprocessing Service",
    "IMAGE_SERVICE":"Image Service",
    "LAYER_PACKAGE":"Layer Package",
    "MAP_SERVICE":"Map Service",
    "MOBILE_APPLICATION":"Mobile Application",
    "RULE_PACKAGE":"Rule Package",
    "VECTOR_TILE_SERVICE":"Vector Tile Service",
    "WEB_MAP":"Web Map",
    "WEB_MAPPING_APPLICATION":"Web Mapping Application",
    "WEB_SCENE":"Web Scene",
    "WMS":"WMS"
  },

  init() {
    this.set('defaults', 
      { SHARING_COMMUNITY_URL: "www.arcgis.com/sharing/rest/community/users/", supportedTypes:{WEB_MAP:"Web Map",MAP_SERVICE:"Map Service",FEATURE_COLLECTION:"Feature Collection",FEATURE_SERVICE:"Feature Service",IMAGE_SERVICE:"Image Service",WEB_SCENE:"Web Scene",CITY_ENGINE_WEB_SCENE:"CityEngine Web Scene",WEB_MAPPING_APPLICATION:"Web Mapping Application",RULE_PACKAGE:"Rule Package",VECTOR_TILE_SERVICE:"Vector Tile Service",GEOPROCESSING_SERVICE:"Geoprocessing Service",MOBILE_APPLICATION:"Mobile Application",DOCUMENT_LINK:"Document Link",LAYER_PACKAGE:"Layer Package",WMS:"WMS"},VALID_TYPES:["Web Map","Map Service","Feature Collection","Feature Service","Image Service","Web Scene","CityEngine Web Scene","Web Mapping Application","Rule Package","Vector Tile Service","Geoprocessing Service","Mobile Application","Document Link","Layer package","WMS"],MONTHS:["January","February","March","April","May","June","July","August","September","October","November","December"],scoring:{DEFAULT:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:6},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:0,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:3},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:8}},WEB_MAP:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},MAP_SERVICE:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},FEATURE_COLLECTION:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},FEATURE_SERVICE:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},IMAGE_SERVICE:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},WEB_SCENE:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:6},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:0,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:3},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:8}},CITY_ENGINE_WEB_SCENE:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:6},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:0,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:3},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:8}},WEB_MAPPING_APPLICATION:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:4,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},RULE_PACKAGE:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:6},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:0,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:3},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:8}},VECTOR_TILE_SERVICE:{THUMBNAILS:{HAS_CUSTOM_SMALL:4,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:2,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:5,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:8},LICENSE_INFORMATION:{MUST_EXIST_SCORE:2,MIN_LENGTH_SCORE:4,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:7},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:8,LAYER_COUNT_BETTER_SCORE:4,LAYER_COUNT_GOOD_SCORE:1},SSL:{SSL_ENABLED:3,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},GEOPROCESSING_SERVICE:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:4,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},MOBILE_APPLICATION:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:4,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},DOCUMENT_LINK:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:4,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}},LAYER_PACKAGE:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:6},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:0,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:3},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:8}},WMS:{THUMBNAILS:{HAS_CUSTOM_SMALL:5,HAS_CUSTOM_LARGE:5},TITLE:{MIN_LENGTH_SCORE:2,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:2,NO_ALL_CAPS_SCORE:2},SUMMARY:{MIN_LENGTH_SCORE:4,NO_PROHIBITED_WORDS_SCORE:3,NO_UNDERSCORE_SCORE:1,MUST_EXIST_SCORE:1},DESCRIPTION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},ACCESS_INFORMATION:{MUST_EXIST_SCORE:9},LICENSE_INFORMATION:{MUST_EXIST_SCORE:1,MIN_LENGTH_SCORE:6,HAS_LINK_SCORE:2},TAGS:{MIN_LENGTH_SCORE:4,MIN_LAW_TAGS_LENGTH_SCORE:4,NO_PROHIBITED_TAGS_SCORE:2},SHARING:{PRIVATE:0,ORG:2,PUBLIC:8},LAYER_COUNT:{LAYER_COUNT_BEST_SCORE:0,LAYER_COUNT_BETTER_SCORE:0,LAYER_COUNT_GOOD_SCORE:0},SSL:{SSL_ENABLED:4,SSL_DISABLED:0},USER_PROFILE_FULLNAME:{HAS_FULLNAME_SCORE:5,HAS_NO_UNDERSCORE_SCORE:2},USER_PROFILE_DESCRIPTION:{USER_PROFILE_DESCRIPTION_HAS_DESCRIPTION:1,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_SENTENCES:2,USER_PROFILE_DESCRIPTION_HAS_MIN_NUM_WORDS:1,USER_PROFILE_DESCRIPTION_HAS_LINK:1,USER_PROFILE_DESCRIPTION_HAS_EMAIL:2},USER_PROFILE_THUMBNAIL:{USER_PROFILE_HAS_THUMBNAIL:7}}}} 
    );    
  }
});
